version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsd_fullstack_api
    ports:
      - "5000:8080"   # HTTP
      - "5001:8081"   # HTTPS
    dns:
    - 8.8.8.8
    - 1.1.1.1
    restart: unless-stopped
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    volumes:
      - ./logs:/app/logs
